config/routes.rb
Rails.application.routes.draw do

  root 'application#home'
  devise_for :users
  resources :users, param: :slug do
    resources :budgets
  end
  resources :budgets do
    resources :transactions
  end
  get '/signup', to: 'users#new'
  get '/profile', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'update', to: 'users#update', as: :update_user
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  before_save { self.name = name.downcase }  
  belongs_to :user, foreign_key: 'user_slug'
  has_many :transactions, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  # validates :goal_date, presence: true,
                        # date: { after: proc { Date.today }, message:
                                # 'Must be a valid & future date' }
  # validates :goal_total, presence: true # , format:
  
  def transactions
    Transaction.where("budget_id = ?", id)
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  # save a transaction total so that the budget can see how much is left to save
  # before_save do
    # self.transaction_total =
      # # Transaction.where(budget_id: @budget.map(&:id)).sum(:transaction_amount)
      # Transaction.sum(:transaction_amount)
  # end
  belongs_to :budget
  default_scope -> { order(created_at: :desc) }
  validates :budget_id, presence: true
  attr_accessor :transaction_amount

  def current_budget
    self.budget_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :budgets, foreign_key: 'budget_id', dependent: :destroy
  has_many :transactions, through: :budgets
  before_save { email.downcase! }
  before_create :set_slug
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w][\w\-\.\+]+@([\w\-]+\.)+[\w\-]{2,4}\z/i # source: Hartl Rails tutorial + a couple of my own tweaks
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 8 }
  has_secure_password

  def budgets
    Budget.where("user_slug = ?", slug)
  end

  def to_param
    slug
  end

  private
    def set_slug
      loop do
        self.slug = SecureRandom.uuid
        break unless User.where(slug: slug).exists?
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def home
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  def show
    @budget = Budget.find(params[:id])
    @transactions = @budget.transactions.paginate(page: params[:page], per_page: 5)
  end

  def create
    @budget = Budget.new(budget_params) 
    @budget.user_slug = params[:user_slug]
    # @budget.goal_date = Date.parse(@budget[:goal_date])
    if @budget.save
      flash.now[:success] = 'Sweet! Budget saved.'
      redirect_to @budget
    else
      flash.now[:danger] = "Darn, that didn't work"
      render 'new'
    end
  end

  def new
    @budget = Budget.new
    @user =  User.find(params[:user_slug])
  end

  private

  def budget_params
    params.require(:budget).permit(:name, :goal_total, :goal_date)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid login credentials'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.budget_id = params[:budget_id]
    if @transaction.save
      flash.now[:success] = 'Yeah! Transaction saved.'
     render 'success'
    else
      flash.now[:danger] = "Uh oh, something isn't right"
     render 'new'
    end
  end

  def new
    @transaction = Transaction.new
    @budget = Budget.find(params[:budget_id])
  end

  private

  def transaction_params
    params.require(:transaction).permit(
      :transaction_date, :transaction_amount, :note, :budget_id 
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :current_user, only: [:show, :create, :edit, :update]
  # before_action :set_user, only: [:show, :edit, :destroy]
  # before_action :authenticate_user!, except: [:new, :create]

  def show
    if params[:slug].to_s.length <= 5
      redirect_to root_path
      flash[:danger] = "Sorry, that wasn't an accessible page."
    else
      # @user = User.find(params[:slug])
      @user = User.find_by_slug(params[:slug])
      @budgets = @user.budgets.paginate(page: params[:page], per_page: 5)
   end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      flash.now[:danger] = 'Please try again.'
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:slug])
  end

  def update
    @user = User.find(params[:slug])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated.'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :slug)
    end

    def set_user
      @user = User.find_by_slug(params[:slug])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_slug] = user.slug
  end

  def log_out
    session.delete(:user_slug)
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(slug: session[:user_slug])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<%# Using bootstrap 'cover' example: https://getbootstrap.com/docs/3.3/examples/cover/ %>

<%# <%= stylesheet_link_tag "homepage" %> 
<div class="card bg-info text-white mb-3 text-right" style="max-width: 100%;">
  <div class="card-body">
    <br>
      <%= link_to "Sign up", signup_path, class: "btn btn-primary" %>
      <%= link_to "Log in", login_path, class: "btn btn-primary" %>
      <br><br>
  </div>
</div>

  <div class='jumbotron'>
    <div class='container'>
      <h1 class='display-3'>Budget App</h1>

      <h3 class='masthead-brand'>
        A place for you to create budgets, set your goal date, and track your progress to completion.
      </h3>
    </div>

app/views/budgets/new.html.erb
<h1>Create a new budget</h1>

<%#Wrap in divs to add styling%>
<%= form_for([@user, @budget]) do |f| %>

    <% if @budget.errors.full_messages.any? %>
  <% @budget.errors.full_messages.each do |error_message| %>
    <%= error_message %> <br />
  <% end %>
<% end %>

  <%= f.label 'Budget name' %>
  <%= f.text_field :name %>
  </br>
  <%= f.label :goal_date %>
  <%= f.date_field :goal_date %>
  </br>
  <%= f.label :goal_total %>
  <%= f.text_field :goal_total %>
  </br>
  <%= f.submit "Create budget" %>
<% end %>

app/views/budgets/show.html.erb
<h1><%= @budget.name %></h1>
<p>
Goal amount: <%= @budget.goal_total %>
</p>

<p>
Date to save amount by: <%= @budget.goal_date %>
</p>

<p>
How much left to save: <%= @budget.goal_total - @budget.transactions.sum(:transaction_amount) %> 
</p>

<h3><u>Transactions</u></h3>
<p><%= link_to 'Add new transaction', new_budget_transaction_path(budget_id: @budget)  %></p>
<ul class='transactions'>
<% @transactions.each do |t| %>
  <li><%= t.note %>: <%= t.transaction_amount %> (<%= t.transaction_date %>)</li>
<% end %>
</ul>

<%= will_paginate @transactions %>

<p>
<%= link_to 'Back to profile', current_user%>
</p>

app/views/layouts/_form.html.erb
<%= form_for(@user, url: yield(:form_path)) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-expand-md navbar-dark fixed-top bg-dark'>

  <div class='collapse navbar-collapse' id='headerNavbar'>
    <ul class='navbar-nav mr-auto'>
      <span>
        <li class='nav-item active'> 
          <%= link_to 'Home', root_path %>
        </li>
      </span>
      <% if logged_in? && !current_page?(update_user_path) && !current_page?(login_path) %>
        <span>
          <li class='nav-item'>
            <%= link_to 'Edit Profile', edit_user_path(current_user) %>
          </li>
        </span>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_page?(controller: 'application', action: 'home') %>
      <%= render 'layouts/header' %>
    <% end %>
    <div class='container'>
      <% flash.each do |message_type, message| %>
        <div class='alsert alert-#{message_type}'><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/transactions/new.html.erb
<h1>Enter a transaction</h1>
<div>
  <p>Amount left to save: $xxxx</p>
  <%= form_for([@budget, @transaction]) do |t| %>

    <% if @transaction.errors.full_messages.any? %>
  <% @transaction.errors.full_messages.each do |error_message| %>
    <%= error_message %> <br />
  <% end %>
<% end %>
    
    <%= t.label 'Transaction amount' %>
    <%= t.number_field :transaction_amount, class: 'form-control' %> 

    <%= t.label 'Transaction date' %>
    <%= t.date_field :transaction_date, class: 'form-control' %>

    <%= t.label 'Add a note' %>
    <%= t.text_field :note, class: 'form-control' %>

    <%# <%= t.label 'Budget id' %> 
    <%# <%= t.text_field :budget_id, class: 'form-control' %> 

    <%= t.submit 'Save transaction', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/transactions/success.html.erb
<h1>You did a save!</h1>
<%= link_to "Back to your budget list", current_user %>

app/views/users/_form.html.erb
 <%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Create an account</h1>

<%#add divs here for more styling%>
<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  </br>
  <%= f.label :email %>
  <%= f.email_field :email %>
  </br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  </br>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  </br>
  <%= f.submit "Come on in" %>
<% end %>

app/views/users/show.html.erb
<h1>
  <%= @user.name %>
 </h1>
 <h2>
   Budget list
 </h2>
 <p>
 <% @budgets.each do |b| %>
   <tr>
     <td><%= link_to b.name, budget_path(b.id) %></td>
     <td>Goal total: <%= b.goal_total %></td>
     <td>Goal date: <%= b.goal_date %></td>
   </tr>
   <br>
 <% end %>
 </p>
 <h2>
   <%= link_to 'Create a new budget', new_user_budget_path(user_slug: @user.slug)  %>
 </h2>
 </p>